#!/usr/bin/env python
import os

# Путь к godot-cpp (рядом с папкой gdextension)
godot_cpp_path = "godot-cpp"

# Загружаем SConstruct от godot-cpp
env = SConscript(os.path.join(godot_cpp_path, "SConstruct"))

# Наши исходники
env.Append(CPPPATH=["src/"])

sources = Glob("src/*.cpp")

# Имя библиотеки
library = env.SharedLibrary(
    "bin/station_mirny{}{}".format(env["suffix"], env["SHLIBSUFFIX"]),
    source=sources,
)

Default(library)
